### ISSUE TITLE
GraphiQL Explorer error message for subscriptions after switching to graphql-ws

### ISSUE THREAD

**Issue by fabiangfd** [mirumee/ariadne#1079]
Hi,

I am using the latest Ariadne 0.19 and just switched from the deprecated `subscriptions-transport-ws` protocol to `graphql-ws` for my GraphQL subscriptions. The change went smoothly for my client application, but now GraphiQL explorer displays the following error message, when I try to test a subscription via GraphiQL:

```json
{
  "errors": [
    {
      "message": "Your GraphiQL createFetcher is not properly configured for websocket subscriptions yet. Please provide subscriptionUrl, wsClient or legacyClient option first.",
      "stack": "Error: Your GraphiQL createFetcher is not properly configured for websocket subscriptions yet. Please provide subscriptionUrl, wsClient or legacyClient option first.\n    at https://unpkg.com/graphiql/graphiql.min.js:2:737044\n    at https://unpkg.com/graphiql/graphiql.min.js:2:567238\n    at onClick (https://unpkg.com/graphiql/graphiql.min.js:2:638040)\n    at HTMLUnknownElement.callCallback (https://unpkg.com/react-dom@17/umd/react-dom.development.js:3942:16)\n    at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@17/umd/react-dom.development.js:3991:18)\n    at invokeGuardedCallback (https://unpkg.com/react-dom@17/umd/react-dom.development.js:4053:33)\n    at invokeGuardedCallbackAndCatchFirstError (https://unpkg.com/react-dom@17/umd/react-dom.development.js:4067:27)\n    at executeDispatch (https://unpkg.com/react-dom@17/umd/react-dom.development.js:8273:5)\n    at processDispatchQueueItemsInOrder (https://unpkg.com/react-dom@17/umd/react-dom.development.js:8305:9)\n    at processDispatchQueue (https://unpkg.com/react-dom@17/umd/react-dom.development.js:8318:7)"
    }
  ]
}
```  

Here is how I initialize my GraphQL ASGI-App:

```python

from ariadne.asgi import GraphQL
from ariadne.asgi.handlers import GraphQLTransportWSHandler

graphql = GraphQL(
    schema,
    debug=True,
    context_value=get_context_value,
    websocket_handler=GraphQLTransportWSHandler(),
    explorer=ExplorerGraphiQL(title="My API Explorer", explorer_plugin=True),
)
```

**Comment by kevinvalk** [comment]
Same here, but I do not think it is due to `GraphQLTransportWSHandler` because when I switch to ExplorerApollo or Playground it all works wonderful. So maybe just configuration of GraphiQL?

**Comment by iblislin** [comment]
A quick hack:
```patch
--- ariadne/explorer/templates/graphiql.html.orig
+++ ariadne/explorer/templates/graphiql.html
@@ -70,6 +70,7 @@
     <script>
       var fetcher = GraphiQL.createFetcher({
         url: window.location.href,
+        subscriptionUrl: `${(window.location.protocol === 'https:' ? 'wss:' : 'ws')}://${window.location.host}${window.location.pathname}`,
       });

       function AriadneGraphiQL() {
```

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one has shipped and can be closed.

Evidence:
- Fix landed in [#1125](https://github.com/mirumee/ariadne/pull/1125) ("Enable Subscription Functionality for GraphiQL-Explorer"), merged 2023-10-25 in commit [`b468817`](https://github.com/mirumee/ariadne/commit/b4688178e04b25576128a27d753cc3c4f4089b48). It adds the `subscriptionUrl` parameter to the GraphiQL fetcher (and a `subscription_url` Jinja knob to override it). See [`ariadne/explorer/templates/graphiql.html#L81-L88`](https://github.com/mirumee/ariadne/blob/main/ariadne/explorer/templates/graphiql.html#L81-L88), which on `main` now reads:
  ```jinja
  const fetcher = createGraphiQLFetcher({
    url: window.location.href,
    {% if subscription_url %}
    subscriptionUrl: "{{ subscription_url }}",
    {% else %}
    subscriptionUrl: (window.location.protocol === "https:" ? "wss" : "ws") + "://" + window.location.host + window.location.pathname,
    {% endif %}
  });
  ```
- Two other users in this thread independently confirmed the fix and asked for closure ([here](https://github.com/mirumee/ariadne/issues/1079#issuecomment-1842858168) and [here](https://github.com/mirumee/ariadne/issues/1079#issuecomment-1842871028)).

If I'm wrong about the fix matching the original scenario, point me at the version/repro and I'll dig further. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code (Anthropic) while triaging stale issues; the references above were verified manually.*
