### ISSUE TITLE
Nested subscriptions not supported

### ISSUE THREAD

**Issue by fischejo** [mirumee/ariadne#1184]
I have problems to implement a nested subscription. I am using:

- ariadne v3.2.3 with ASGI
- uvicorn v0.29.0
- websockets v12.0

The GraphQL schema looks like that:
```graphql
    schema {
        query: Query
        subscription: Subscription
    }
    type Query {
        placeholder: Boolean
    }
    type Subscription {
        nested: NestedSubscription!
    }
    type NestedSubscription {
        counter: Int!
    }
```

and the resolvers are linked as follows:
```python
nested_subscription = SubscriptionType() 
nested_subscription.name = "NestedSubscription" # overwrite name of type
nested_subscription.set_field("counter", counter_resolver)
nested_subscription.set_source("counter", counter_generator)

# link nested subscription to subscription 
# here, the nested subscription is linked as any other Query- or Mutation-resolver.
subscription = ObjectType("Subscription")
subscription.set_field("nested", nested_subscription)
```

which raises `TypeError: Subscription field must return AsyncIterable. Received: None.:
```
Traceback (most recent call last):
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/ariadne/asgi/graphql.py", line 183, in __call__
    await self.websocket_handler.handle(scope=scope, receive=receive, send=send)
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/ariadne/asgi/handlers/graphql_transport_ws.py", line 95, in handle
    await self.handle_websocket(websocket)
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/ariadne/asgi/handlers/graphql_transport_ws.py", line 120, in handle_websocket
    await self.handle_websocket_message(websocket, message, client_context)
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/ariadne/asgi/handlers/graphql_transport_ws.py", line 186, in handle_websocket_message
    await self.handle_websocket_subscribe(
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/ariadne/asgi/handlers/graphql_transport_ws.py", line 340, in handle_websocket_subscribe
    success, results_producer = await subscribe(
                                ^^^^^^^^^^^^^^^^
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/ariadne/graphql.py", line 563, in subscribe
    result = await _subscribe(
             ^^^^^^^^^^^^^^^^^
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/graphql/execution/subscribe.py", line 58, in subscribe
    result_or_stream = await create_source_event_stream(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fischejo/projects/graphql-nested-subscription/venv/lib/python3.11/site-packages/graphql/execution/subscribe.py", line 152, in create_source_event_stream
    raise TypeError(
TypeError: Subscription field must return AsyncIterable. Received: None.
```

I have the feeling, that nested subscriptions are uncommon, but it is possible in other languages & frameworks. As I have the requirement to provide the subscription in a nested type, I would like to implement/fix it. Does someone have a hint were I should look at first?

This [repository](https://github.com/fischejo/ariadne-nested-subscription) provides the complete test source code.

**Comment by rafalp** [comment]
Nested subscriptions are not part of the GraphQL spec. All your async sources need to set on `Subscription` fields.

**Comment by fischejo** [comment]
Thank you for your reply. I was not aware of that.
