### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by mdwint** [mirumee/ariadne#144]
This problem occurs on Python 3.7 in AWS Lambda (but not locally).

```
[ERROR] AttributeError: type object 'Callable' has no attribute '_abc_registry'
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/var/lang/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/itpieces/api/graphql_/__init__.py", line 3, in <module>
    from ariadne import graphql_sync
  File "/var/task/ariadne/__init__.py", line 1, in <module>
    from .enums import EnumType
  File "/var/task/ariadne/enums.py", line 3, in <module>
    from typing import Any, Dict, Union
  File "/var/task/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/var/task/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
```

I noticed that Ariadne has `typing` as a dependency. Perhaps this is clashing with `typing` from the Python 3.7 standard library?

#### Suggested solution
Only install `typing` when `python_version<"3.5"` (Reference: [Python typing module](https://github.com/python/typing/issues/573))

**Comment by patrys** [comment]
Interesting that it works for us with the backport installed. I'm not sure we actually need the `typing` dependency at all. We already depend on `typing_extensions` which should provide all the necessary types across Python versions 3.5-3.7. @rafalp?

**Comment by mdwint** [comment]
I was able to work around the issue by excluding `typing` from the deployment package.

**serverless.yml**:
```
custom:
  pythonRequirements:
    noDeploy:
    - typing
```

**Comment by rafalp** [comment]
We only support 3.6+, so I'll cook up a PR today to drop explicit `typing` dependency.
