### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by HypnosY** [mirumee/ariadne#148]
Getting an error when starting jupyter notebook.
I can't fix it , can anybody help me ? 
I rebuild my jupyter notebook ,seems it isn't his fault.

Last login: Wed Apr 24 23:06:17 
 miracleleon@MiracledeMBP  ~  jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 610, in <module>
    from .extensions import (
  File "/usr/local/lib/python3.7/site-packages/notebook/extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
  File "/usr/local/lib/python3.7/site-packages/tornado/log.py", line 34, in <module>
    from tornado.escape import _unicode
  File "/usr/local/lib/python3.7/site-packages/tornado/escape.py", line 27, in <module>
    from tornado.util import unicode_type
  File "/usr/local/lib/python3.7/site-packages/tornado/util.py", line 18, in <module>
    import typing
  File "/usr/local/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

**Comment by HypnosY** [comment]
I just cannot find the solution. So came here for help!

**Comment by patrys** [comment]
I think that's related to the `typing` module. Try uninstalling the `typing` package (`pip uninstall typing` should be enough). We've removed it as a dependency on `master` branch.

**Comment by HypnosY** [comment]
> 我认为这与`typing`模块有关。尝试卸载`typing`软件包（`pip uninstall typing`应该足够了）。我们已将其删除为对`master`分支的依赖。

Thank you very much.It work!

**Comment by rafalp** [comment]
Fixed on master. Thanks!
