### ISSUE TITLE
Dataloader for non-async server

### ISSUE THREAD

**Issue by isopterix** [mirumee/ariadne#240]
@rafalp : on the spectrum discussion you said: 
> As fallback for synchronous servers, you can also preload root_value by introspecting the query: https://ariadnegraphql.org/docs/types-reference#rootvalue - but dataloader will be saner approach to go about.

Could you explain how one would go about this? I cannot make any sense out of the linked documentation and how to use it properly ;(

**Comment by patrys** [comment]
You could introspect the entire `document` (which contains the AST of the query submitted by the client) and prefetch all of the information and return it as the `root_value` in which case you would not need to access the database in your resolvers, returning data from `info.root_value` instead.

**Comment by patrys** [comment]
Here you can see this pattern implemented for Django and Graphene: https://github.com/tfoxy/graphene-django-optimizer

As @rafalp said, using data loaders leads to cleaner code.

**Comment by isopterix** [comment]
Thank you, @patrys. I had initially tried to apply the dataloader concept shown in the graphene docs but somehow I cannot get it to work. I get all sorts of RuntimeErrors. The aiodataloader is out of the game as I plan to use djangos backend. SO I am looking for something that would work in a sychronous setting.

It a lot of new territory for me...

**Comment by isopterix** [comment]
I was trying it like this... but that's were I always end up getting the error below. What am I missing? Looks like I have a fundamental misunderstanding of how this is supposed to work... Or is there an incompatibility of some sort?

```python
from promise import Promise
from promise.dataloader import DataLoader

[...]

class UserProfileLoader(DataLoader):                                                                                                                             
    def batch_load_fn(self, keys):                                                                                                                          
        userprofiles = {userprofile.id: userprofile for userprofile in UserProfile.objects.filter(id__in=keys)}
        return Promise.resolve([UserProfile.get(userprofile_id) for userprofile_id in keys])

userprofile_loader= UserProfileLoader()

def test_resolver(obj, info):
    return userprofile_loader.load(obj.id)

user = ObjectType("User")
user.set_field("userprofile", test_resolver)

@query.field("users")
def resolve_users(*_):
    return User.objects.all()

schema = make_executable_schema(
    type_defs, [
        [...]
        user
    ]
)

```

with schema

```gql
type Query {
  users: [User]
}

type User {
  id: ID!
  username: String
  firstName: String
  lastName: String
  lastLogin: DateTime
  email: String
  userprofile: UserProfile
}

type UserProfile {
  id: ID!
  user: User
  orgunit: String
  [...]
}
```

Error:

```python
August 22, 2019 - 14:46:18
Django version 2.2.4, using settings 'ops_backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "C:\APP\dev\ops\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\APP\dev\ops\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\APP\dev\ops\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\APP\dev\ops\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\APP\dev\ops\venv\lib\site-packages\django\utils\decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\APP\dev\ops\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\APP\dev\ops\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\APP\dev\ops\venv\lib\site-packages\ariadne\contrib\django\views.py", line 61, in post
    success, result = self.execute_query(request, data)
  File "C:\APP\dev\ops\venv\lib\site-packages\ariadne\contrib\django\views.py", line 117, in execute_query
    middleware=self.middleware,
  File "C:\APP\dev\ops\venv\lib\site-packages\ariadne\graphql.py", line 160, in graphql_sync
    ensure_future(cast(Awaitable[ExecutionResult], result)).cancel()
  File "C:\Program Files\Python37\lib\asyncio\tasks.py", line 580, in ensure_future
    loop = events.get_event_loop()
  File "C:\Program Files\Python37\lib\asyncio\events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

**Comment by patrys** [comment]
Ariadne does not know how to handle `Promise` objects from the `promise` library.

**Comment by patrys** [comment]
It is asynchronous but executes in its own context, you can call `promise.get()` to resolve it in a synchronous (blocking) fashion.

**Comment by rafalp** [comment]
I feel we shouldn't do anything about this at the moment. There's no way to do this right without in sync execution - with either solution being workaround.
