### ISSUE TITLE
`make_executable_schema`'s  omits default enum values in fields args

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne#293]
GraphQL enums are represented in Python via the [`GraphQLEnumType`](https://github.com/graphql-python/graphql-core-next/blob/master/src/graphql/type/definition.py#L996). If those types are created from the SDL, they define no Python representation for GraphQL enum items. Developers can use Ariadne-provided `EnumType` to specify how enum items should be represented in Python themselves, but we also include "fallback" step that fills enum values with their `str` representations.

However neither of those approaches takes care of enum items defined as default values for field arguments. Eg:

```
type Query {
    users(role: ADMIN): [User]
}
```

We will need to add additional step to `make_executable_schema` that gathers all enums from schema together with their Python representations, and then introspects schema's fields values for places where field has default value type of enum. If this is the case, we should set correct `default_value` on [`GraphQLArgument`](https://github.com/graphql-python/graphql-core-next/blob/b320331faf2fc2f4f1f6a1366f07109d1bdd44f1/src/graphql/type/definition.py#L576) in the schema.

**Comment by Dodobibi** [comment]
Is there a workaround for this ?

**Comment by dkbarn** [comment]
Any update on this? The issue was created quite a while ago and feels like a pretty common use case. I've only been playing with ariadne for a couple days and hit the bug immediately.

**Comment by rafalp** [comment]
PR's welcome :)

In the meantime workaround for this issue is to define default value in Python, eg:

```
def resolve(_, info, *, role=Roles.ADMIN)
```

**Comment by dkbarn** [comment]
It's unclear to me why this is not already done by `graphql.parse()`
This is the function that interprets a raw schema string and converts it into python objects like `GraphQLEnumType` and `GraphQLArgument`, correct?
Why isn't the population of `GraphQLArgument.default_value` happening as part of that step?

**Comment by rafalp** [comment]
`graphql.parse()` doesn't known about custom enum bindings defined in `ariadne.EnumType`.

**Comment by dkbarn** [comment]
The use of custom `ariadne.EnumType` bindings with are optional, I thought. According to https://ariadnegraphql.org/docs/enums#mapping-to-internal-values - the default behaviour is for enums to be represented as strings. So if someone is not making use of custom enum bindings, can `graphql.parse()` take care of it?

**Comment by rafalp** [comment]
That may be the case, but please remember that this issue is mainly about `EnumType` that Ariadne provides.

**Comment by rafalp** [comment]
This is not the case as long as `EnumType` is not used. For this schema:

```graphql
enum Role {
  ADMIN
  USER
}

type Query {
  hello(r: Role = USER): String
}
```

And this query:

```graphql
{
  default: hello
  custom: hello(r: ADMIN)
}
```

Resolver that returns `repr(r)` returns this result:

```json
{
  "default": "'USER'",
  "custom": "'ADMIN'"
}
```

However as soon as `EnumType` is used, python types stop working out:

```json
{
  "default": "'USER'",
  "custom": "<Role.ADMIN: 'ADMIN'>"
}
```

**Comment by rafalp** [comment]
Turns out there's also a gotcha with Schema validation in GraphQL core which skips default values validation against enum definition:

https://github.com/graphql-python/graphql-core/issues/122

**Comment by dkbarn** [comment]
I don't know if this is the right place to discuss this issue (it seems related to enums and default values):

There seems to be a regression in ariadne 0.13.0. Or at least an unexpected change in behaviour when I upgraded from 0.12.0.

If you run the following:
```
import ariadne
import enum
import pprint

type_defs = """
    enum Role {
        ADMIN
        USER
    }

    type Query {
        hello(r: Role = USER): String
    }
"""

class Role(enum.Enum):
    ADMIN = "admin"
    USER = "user"

RoleGraphQLType = ariadne.EnumType("Role", Role)

QueryGraphQLType = ariadne.QueryType()

schema = ariadne.make_executable_schema(
    type_defs,
    QueryGraphQLType,
    RoleGraphQLType,
)

query = "{__schema{types{name,fields{name,args{name,defaultValue}}}}}"

result = ariadne.graphql_sync(schema, {"query": query}, debug=True)
pprint.pprint(result)
```

This works fine under the environment:
```
ariadne 0.12.0
graphql-core 3.0.5
```

But when run under the environment:
```
ariadne 0.13.0
graphql-core 3.1.3
```
It produces the error:
```
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/graphql/execution/execute.py", line 678, in complete_value_catching_error
    completed = self.complete_value(
  File "venv/lib/python3.8/site-packages/graphql/execution/execute.py", line 745, in complete_value
    raise result
  File "venv/lib/python3.8/site-packages/graphql/execution/execute.py", line 637, in resolve_field_value_or_error
    result = resolve_fn(source, info, **args)
  File "venv/lib/python3.8/site-packages/graphql/type/introspection.py", line 399, in default_value
    value_ast = ast_from_value(item[1].default_value, item[1].type)
  File "venv/lib/python3.8/site-packages/graphql/utilities/ast_from_value.py", line 108, in ast_from_value
    serialized = type_.serialize(value)  # type: ignore
  File "venv/lib/python3.8/site-packages/graphql/type/definition.py", line 1146, in serialize
    raise GraphQLError(
graphql.error.graphql_error.GraphQLError: Enum 'Role' cannot represent value: 'USER'
```

**Comment by bnaoki** [comment]
Perhaps this is obvious but, to add on to @dkbarn's previous comment, as it stands the default introspection query used by tools like GraphiQL and GraphQL Playground do not work. This results in the documentation tab and the auto-fill being broken in those tools.

**Comment by rafalp** [comment]
@dkbarn that looks like a bug all-right, but it should be separate issue on our tracker. Can you post it as separate bug? Thanks!

**Comment by dkbarn** [comment]
Sure thing, separate issue created here: https://github.com/mirumee/ariadne/issues/547
