### ISSUE TITLE
Federation: exception for async reference resolver

### ISSUE THREAD

**Issue by vreon** [mirumee/ariadne#307]
Hi all! I'm tinkering with the just-merged Federation support :tada: I'm trying to define a reference resolver that returns a coroutine (`aiodataloader`):

```py
@User.reference_resolver
def resolve_reference(type_object, info, reference):
    type, id = from_global_id(reference["id"])  # parses a Relay ID
    return info.context.users.get_by_id.load(int(id))
```

But that raises an exception in `add_typename_to_possible_return`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 343, in execute_operation
    self.execute_fields_serially
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 435, in execute_fields
    result = self.resolve_field(
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 606, in resolve_field
    return self.complete_value_catching_error(
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 683, in complete_value_catching_error
    self.handle_field_error(error, field_nodes, path, return_type)
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 698, in handle_field_error
    raise error
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 669, in complete_value_catching_error
    completed = self.complete_value(
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 735, in complete_value
    raise result
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/execute.py", line 625, in resolve_field_value_or_error
    result = resolve_fn(source, info, **args)
  File "/usr/local/lib/python3.8/site-packages/ariadne/contrib/federation/utils.py", line 83, in resolve_entities
    add_typename_to_possible_return(
  File "/usr/local/lib/python3.8/site-packages/ariadne/contrib/federation/utils.py", line 132, in add_typename_to_possible_return
    setattr(obj, f"_{obj.__class__.__name__}__typename", typename)
graphql.error.graphql_error.GraphQLError: 'coroutine' object has no attribute '_coroutine__typename'
```

If I change the reference resolver to return a `dict` with some test data, it works fine, but I need to use that dataloader to do a real lookup.

Any thoughts on where the problem lies?

(also, I'm new to asyncio, and originally had `async def resolve_reference(...):` and `return await ...`, which I realized is sort of pointless. Mentioning it here in case it's relevant.)

**Comment by bogdal** [comment]
@vreon thanks for pointing at this. We are aware of this problem and we plan to fix it before next Ariadne release 🚀 Stay tuned✋
