### ISSUE TITLE
Cannot import name 'GraphQLNamedType'

### ISSUE THREAD

**Issue by wkup** [mirumee/ariadne#359]
I am using version 0.11.0 of ariadne with FastAPI (0.54.1).
When I launch the server, I have a systematic error of which here is the stack.

```
uvicorn app.main:app --reload

INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [7818]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app/main.py", line 21, in <module>
    from ariadne.asgi import GraphQL
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ariadne/__init__.py", line 1, in <module>
    from .enums import EnumType
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ariadne/enums.py", line 5, in <module>
    from graphql.type import GraphQLEnumType, GraphQLNamedType, GraphQLSchema
ImportError: cannot import name 'GraphQLNamedType' from 'graphql.type' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/graphql/type/__init__.py)
```

**Comment by wkup** [comment]
```
pip3 show graphql-core
version : 2.0.14
```
uninstall and reinstall
```
pip3 uninstall graphql-core
pip3 install graphql-core==3.0.3 
```
