### ISSUE TITLE
Naming your program graphql.py causes ariadne imports to fail

### ISSUE THREAD

**Issue by mcho421** [mirumee/ariadne#400]
If you call your program `graphql.py`, none of the imports from `ariadne` appear to work. Here's a minimal example:

graphql.py:
```
from ariadne import Query type
```

Then run

```
python graphql.py
```

It fails with this error:

```
Traceback (most recent call last):
  File "graphql.py", line 1, in <module>
    from ariadne import QueryType
  File "/Users/mcho421/.virtualenvs/hellothere/lib/python3.6/site-packages/ariadne/__init__.py", line 1, in <module>
    from .enums import EnumType
  File "/Users/mcho421/.virtualenvs/hellothere/lib/python3.6/site-packages/ariadne/enums.py", line 5, in <module>
    from graphql.type import GraphQLEnumType, GraphQLNamedType, GraphQLSchema
  File "/Users/mcho421/Projects/hellothere/graphql.py", line 1, in <module>
    from ariadne import QueryType
ImportError: cannot import name 'QueryType'
```

If you rename `graphql.py` to anything else, everything appears to work.

Tested on Mac OSX 10.15.4, Python 3.6.10 running in a virtualenv, ariadne==0.11.0

**Comment by rafalp** [comment]
This happens because `graphql` is already used by the `graphql-core` package. Use namespace (eg. `myproject.graphql`) or something else.

**Comment by oscarmrom** [comment]
I'm getting started with Python and Ariadne and the same thing happens if you name the file `ariadne.py`

Just in case someone else runs into this issue.
