### ISSUE TITLE
graphql-core v3.2 breaks directives

### ISSUE THREAD

**Issue by sda97ghb** [mirumee/ariadne#780]
Since [this commit](https://github.com/graphql-python/graphql-core/commit/b9423b74ca9d22d009a1a4633b38b2bcd06c604b) in graphql-core replaced all lists with tuples, `schema.directives` is a tuple now.

This causes an error in [ariadne.schema_visitor.each](https://github.com/mirumee/ariadne/blob/3921fb1d7cd156eb7b5dc39e9a0695508f187cdd/ariadne/schema_visitor.py#L58).

It seems like a possible solution is to replace `isinstance(list_or_dict, list)` with `isinstance(list_or_dict, Sequence)`.

**Comment by kolypto** [comment]
I've also encountered this bug. The result is: Ariadne fails immediately when a custom directive is defined.

Unit test:

```python
import ariadne


# Implement a dummy directive
class TestDirective(ariadne.SchemaDirectiveVisitor):
    pass


schema = ariadne.make_executable_schema(
    # Provide a dummy schema
    'type Query { hello: String }',
    # When `directives` is not empty, it triggers the `each()` code
    directives={'test': TestDirective}
)
```

Result:

```
Traceback (most recent call last):
  File "play.py", line 9, in <module>
    schema = ariadne.make_executable_schema(
  File "ariadne/executable_schema.py", line 38, in make_executable_schema
    SchemaDirectiveVisitor.visit_schema_directives(schema, directives)
  File "ariadne/schema_visitor.py", line 394, in visit_schema_directives
    declared_directives = cls.get_declared_directives(schema, directive_visitors)
  File "ariadne/schema_visitor.py", line 341, in get_declared_directives
    each(schema.directives, _add_directive)
  File "ariadne/schema_visitor.py", line 63, in each
    for key, value in list_or_dict.items():
AttributeError: 'tuple' object has no attribute 'items'
```

This happens because `schema.directives` is now a tuple, and `each()` has the following condition:

```python
def each(list_or_dict: IndexedObject, callback: Callback):
    if isinstance(list_or_dict, list):  # <-- does not detect tuples
        for value in list_or_dict:
            callback(value)
    else:
        for key, value in list_or_dict.items():
            callback(value, key)
```

like @sda97ghb mentioned, replacing the condition with `abc.Sequence` will help.
